# Generated by Django 6.0.3 on 2026-03-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('topic', models.CharField(choices=[('django_model', 'Django Model'), ('django_api', 'Django API'), ('react_axios', 'React + Axios'), ('sql_migration', 'SQL + Migration'), ('algorithm', 'Algorithm')], max_length=40)),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('doing', 'Doing'), ('done', 'Done')], default='todo', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'playground_task',
                'ordering': ['status', '-updated_at', '-id'],
            },
        ),
    ]
