# Generated by Django 6.0.3 on 2026-03-08 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcurrencyLabItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('stock', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'playground_concurrency_item',
            },
        ),
        migrations.CreateModel(
            name='ConcurrencyLabEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('unlocked', 'Unlocked'), ('locked', 'Locked')], max_length=16)),
                ('actor', models.CharField(default='anonymous', max_length=64)),
                ('requested_qty', models.PositiveIntegerField(default=1)),
                ('success', models.BooleanField(default=False)),
                ('before_stock', models.IntegerField(default=0)),
                ('after_stock', models.IntegerField(default=0)),
                ('message', models.CharField(default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='playground.concurrencylabitem')),
            ],
            options={
                'db_table': 'playground_concurrency_event',
                'ordering': ['-id'],
            },
        ),
    ]
