# Generated by Django 6.0.3 on 2026-03-07 20:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_book_publisher_author_book_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('borrowed_on', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='manager.book')),
            ],
            options={
                'db_table': 'borrow_record',
                'ordering': ['-borrowed_on', '-id'],
            },
        ),
    ]
