# Generated by Django 6.0.3 on 2026-03-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_borrowrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('librarian', 'Librarian'), ('analyst', 'Analyst')], default='admin', max_length=16),
        ),
    ]
