# Generated by Django 6.0.3 on 2026-03-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_manager_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst')], default='admin', max_length=16),
        ),
    ]
